language: d
sudo: false

matrix:
    include:
        - d: dmd-2.082.0
        - d: dmd-2.081.2
        - d: dmd-2.080.1
        - d: ldc-1.11.0
        - d: ldc-1.10.0

# Ddox dependencies
addons:
  apt:
    packages:
      - libevent-dev

script:
  - build/ci.sh
  # - dub build -b ddox

after_success:
 - bash <(curl -s https://codecov.io/bash)

# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: $TRAVIS_BUILD_DIR/docs
#   github_token: $GH_REPO_TOKEN
#   on:
#     branch: master
