language: d
sudo: false


matrix:
  include:
    - d: dmd-2.084.0
    - d: dmd-2.083.1
    - d: ldc-1.13.0
    - d: ldc-1.12.0


script:
  - build/ci.sh
  # - dub build -b ddox


after_success:
 - bash <(curl -s https://codecov.io/bash)
