language: d
sudo: false


matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.091.1
   # - d: ldc-1.21.0 # FIXME
  allow_failures:
    - d: dmd-nightly

script:
  - build/ci.sh
  # - dub build -b ddox


after_success:
 - bash <(curl -s https://codecov.io/bash)
