language: d
sudo: false


matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.090.0
    - d: dmd-2.087.1
    - d: ldc-1.17.0
    - d: ldc-1.16.0
  allow_failures:
    - d: dmd-nightly

script:
  - build/ci.sh
  # - dub build -b ddox


after_success:
 - bash <(curl -s https://codecov.io/bash)
