language: d
sudo: false

matrix:
    include:
        - d: dmd
        - d: dmd-2.077.1
        - d: dmd-2.076.1
        - d: dmd-2.075.1
        - d: dmd-2.074.1
        - d: dmd-2.073.2
        - d: dmd-2.072.2
        - d: ldc
        - d: ldc-1.6.0
        - d: ldc-1.5.0
        - d: ldc-1.4.0
        - d: ldc-1.3.0
        - d: ldc-1.2.0

# Ddox dependencies
addons:
  apt:
    packages:
      - libevent-dev

script:
  - ./test.sh
  - integration/run.sh
  # - dub build -b ddox

# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: $TRAVIS_BUILD_DIR/docs
#   github_token: $GH_REPO_TOKEN
#   on:
#     branch: master
