language: d
sudo: false

matrix:
    include:
        - d: dmd
        - d: dmd-2.076.1
        - d: dmd-2.075.1
        - d: dmd-2.074.1
        - d: dmd-2.073.2
        - d: dmd-2.072.2
        - d: ldc
        - d: ldc-1.4.0

script:
  - ./test.sh
  - integration/run.sh
